<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Web.BackOffice" Version="13.9.3" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="13.9.3" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
		<PackageReference Include="uSync.BackOffice" Version="10.3.2" />
	</ItemGroup>


	<ItemGroup>
	  <ProjectReference Include="..\uSync.Migrations.Core\uSync.Migrations.Core.csproj" />
	</ItemGroup>

</Project>
